apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-nexus
  template:
    metadata:
      labels:
        app: proxy-nexus
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-nexus-svc
spec:
  selector:
    app: proxy-nexus
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
